version: '3.8'

services:
  # Spring Boot Backend Service
  biblioteca:
    build:
      context: ./biblioteca # Assumes Dockerfile exists in ./biblioteca
      dockerfile: Dockerfile
    container_name: springboot_biblioteca
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    networks:
      - app-network

# Define Networks
networks:
  app-network:
    driver: bridge
